apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ecommerce
  labels:
    app: shopnow
    component: redis
spec:
  type: ClusterIP
  selector:
    app: shopnow
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
