# Generated by Django 5.1.14 on 2026-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'permissions': [('advance_status', 'Can advance order status through the fulfillment pipeline'), ('refund_full', 'Can issue a full refund'), ('refund_partial', 'Can issue a partial refund')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
