# Generated by Django 5.1.14 on 2026-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionlog',
            options={'ordering': ('-created',), 'permissions': [('view_audit_log', 'Can view the audit log')], 'verbose_name': 'Admin action log', 'verbose_name_plural': 'Admin action logs'},
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('error', 'Error')], db_index=True, default='success', max_length=10),
        ),
    ]
