# Generated by Django 5.1.14 on 2026-08-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adminactionlog_options_adminactionlog_outcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionlog',
            options={'ordering': ('-created',), 'permissions': [('view_audit_log', 'Can view the audit log'), ('view_dashboard', 'Can view the admin dashboard overview/stats')], 'verbose_name': 'Admin action log', 'verbose_name_plural': 'Admin action logs'},
        ),
    ]
