apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-ingress-user-ui
  namespace: ecommerce
  labels:
    app: shopnow
  annotations:
    traefik.ingress.kubernetes.io/proxy-body-size: "20m"
    traefik.ingress.kubernetes.io/proxy-read-timeout: "120"
    traefik.ingress.kubernetes.io/proxy-send-timeout: "120"
    traefik.ingress.kubernetes.io/use-forwarded-headers: "true"
    # Start with staging — swap to letsencrypt-prod once verified
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Reference to cert-manager issuer for TLS
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - shopnow.johnisah.com
      secretName: shopnow-user-ui-tls    # cert-manager writes the cert here
  rules:
    - host: shopnow.johnisah.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000

          - path: /django-admin/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000

          - path: /media/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000

          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-ui
                port:
                  number: 3000
