apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ecommerce
  labels:
    app: shopnow
    component: api
spec:
  type: ClusterIP
  selector:
    app: shopnow
    component: api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
