apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: ecommerce
  labels:
    app: shopnow
    component: admin-ui
spec:
  type: ClusterIP
  selector:
    app: shopnow
    component: admin-ui
  ports:
    - port: 3001
      targetPort: 3001
      name: http
