apiVersion: v1
kind: Service
metadata:
  name: user-ui
  namespace: ecommerce
  labels:
    app: shopnow
    component: user-ui
spec:
  type: ClusterIP
  selector:
    app: shopnow
    component: user-ui
  ports:
    - port: 3000
      targetPort: 3000
      name: http
