# Generated by Django 5.1.14 on 2026-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'permissions': [('manage_inventory', 'Can update stock levels only'), ('manage_pricing', 'Can update prices only')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',), 'permissions': [('moderate_reviews', 'Can approve, reject, or delete reviews')], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
