# Generated by Django 5.1.14 on 2026-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'permissions': [('manage_users', 'Can manage user accounts (deactivate, reset password)'), ('revoke_sessions', 'Can force-revoke a user session')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
