# Generated by Django 5.1.14 on 2026-08-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'permissions': [('manage_users', 'Can manage customer accounts (deactivate, reset password)'), ('revoke_sessions', 'Can force-revoke a user session'), ('manage_staff', 'Can provision new team member (internal staff) accounts')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
