apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shopnow-user-ui-pdb
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: shopnow
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shopnow
      component: user-ui
