apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce
  labels:
    app: shopnow
    component: postgres
spec:
  type: ClusterIP          # Internal only — not exposed outside the cluster
  selector:
    app: shopnow
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
