apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-storage
  namespace: argocd
  labels:
    app.kubernetes.io/name: shopnow-storage
    app.kubernetes.io/part-of: shopnow
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # StorageClass needed before postgres's PVC
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopnow
  source:
    repoURL: https://github.com/johnitopaisah/ecommerce-platform
    targetRevision: develop
    path: k8s/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
