apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: shopnow-ingress
    app.kubernetes.io/part-of: shopnow
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # after services and cert-manager are ready
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopnow
  source:
    repoURL: https://github.com/johnitopaisah/ecommerce-platform
    targetRevision: develop
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/annotations/cert-manager.io~1certificate-name   # injected by cert-manager
